#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: at 1am every day
  # daily_stock_dividend_job:
  #   class: Daily::StockDividendJob
  #   queue: default
  #   schedule: at 11am every day
  # daily_stats_harvest:
  #   class: Daily::PersonalStatsJob
  #   queue: default
  #   schedule: at 11am every day
# development:
#   daily_stock_dividend_job:
#     class: Daily::StockDividendJob
#     queue: default
#     schedule: every 20 seconds
#   daily_stats_harvest:
#     class: Daily::PersonalStatsJob
#     queue: default
#     schedule: every 20 seconds

